### ISSUE TITLE
Define order for checks

### ISSUE THREAD

**Issue by swapab** [theforeman/foreman_maintain#12]
Define which check executes in what order.
Maybe an extra metadata or a configuration file to list down the checks in numerical order. Mostly beneficial for users/customers.

_Pros_:
1. Categorize the type of checks.
2. Can be customized by users.
3. Easy to go with an offline checklist.

_Cons_:
1. Extra configuration apart from existing foreman configs(not sure how many are there)
2. User intervention results in educating the users/Cu.

This could be a good to have feature.

**Comment by iNecas** [comment]
Doing this via metadata might be good, using ruby tsort (http://ruby-doc.org/stdlib-2.0.0/libdoc/tsort/rdoc/TSort.html) it's catually even not to hard to calculate the ependencies at the end.

I would like to avoid numerical ordering, as it's a bit fragile. One way to solve it with current code base is introducing more tags, and we would add the checks from the specific tags one by one in the scenario.

I would suggest talking about specific example and first trying to go without this, to have more inputs before we introduce a solution for it.

**Comment by iNecas** [comment]
Tracking as http://projects.theforeman.org/issues/19564
