### ISSUE TITLE
Clean errored tasks in 6.2.z, if they are from previous sat version 6.0 or 6.1

### ISSUE THREAD

**Issue by san7ket** [theforeman/foreman_maintain#14]
While upgrade, there are two pending tasks since 6.0 install. If we resume them they error out. So would be great if such tasks could be self healed or user should be able to remove them  (w/ a prompt) or at least if they are non-blockers for upgrade we could convert them to warning. 
Paused task on system named as "Actions::Katello::ContentView::NodeMetadataGenerate"

**Comment by iNecas** [comment]
Tracking as http://projects.theforeman.org/issues/20159, closing the issue as we are moving away from github issue tracker to Redmine http://projects.theforeman.org/projects/foreman-maintain.

This issue also should be already implemented, which checking old paused tasks. We are currently whitelisting just some of them, to not delete something we should not to. See https://github.com/theforeman/foreman_maintain/blob/master/definitions/features/foreman_tasks.rb#L4
