### ISSUE TITLE
Check: Verify self registration

### ISSUE THREAD

**Issue by lzap** [theforeman/foreman_maintain#23]
It would be good to create a check that searches for `katello-ca-consumer-*.rpm` installed and compares the hostname in the RPM package with hostname of the system.

If they are same, I'd issue WARNING: This system is self-registered.

Server can be sometimes self-registered, therefore this is not an ERROR but WARNING. We've encountered an issue when Capsule was self-registered and we did not notice that, it took lot of time to figure out. A warning could should this immediately.

**Comment by swapab** [comment]
@lzap This check has been implemented in PR https://github.com/iNecas/foreman_maintain/pull/53
Can you please try it out and let us know if it works as you expected?

Also, do you think it would be a good idea to convey the user about workaround(or resolution steps) for the WARNING?

**Comment by lzap** [comment]
Sorry for late response, I think the warning is only relevant on Capsule. On Server, they are sometimes self-registered and it should not be a warning, that's [OK]. Apologize for confusion:

Server:
* CDN or self registered - OK
* WARNIN otherwise

Capsule:
* CDN or self registered - WARNING: Capsule should have been registered to Satellite Server
* OK otherwise

**Comment by iNecas** [comment]
Tracking as http://projects.theforeman.org/issues/19715, closing the issue as we are moving away from github issue tracker to Redmine http://projects.theforeman.org/projects/foreman-maintain.
