### ISSUE TITLE
Check: Verify if EPEL is enabled

### ISSUE THREAD

**Issue by lzap** [theforeman/foreman_maintain#24]
We had a case when EPEL was enabled on a Capsule and qpidd was upgraded from there to more recent version. We should inform users this as an ERROR that EPEL must not be enabled.

**Comment by iNecas** [comment]
Tracking as http://projects.theforeman.org/issues/20156, closing the issue as we are moving away from github issue tracker to Redmine http://projects.theforeman.org/projects/foreman-maintain.
