### ISSUE TITLE
Check: Issue warning if there are errors in logs

### ISSUE THREAD

**Issue by lzap** [theforeman/foreman_maintain#34]
We could grep all known logs for (ERROR|error|fatal) or similar and in case there are some we could put the check into WARNING state. I would not do ERROR state because this will often show false alarm.

**Comment by swapab** [comment]
Questions:
1. Which log files to check?(`production.log` is one of it)
2. Should we count all the errors? Or just check for recent error only?

**Comment by lzap** [comment]
I'd check `/var/log/foreman/production.log` and `/var/log/foreman-proxy/proxy.log`, skip them if not present (on Capsule only `proxy.log` will be there). Each one has different format tho.

Both files are rotated daily so checking whole file is fine.

**Comment by swapab** [comment]
http://projects.theforeman.org/issues/20153
