### ISSUE TITLE
Command: Wipe capsule and start over

### ISSUE THREAD

**Issue by lzap** [theforeman/foreman_maintain#41]
Pulp does not handle broken repositories well, it just reports errors like "Will not create a symlink to a non-existent source" but a repo will never start working again. We need a command that will wipe all capsule package data (and mongo) and starts again:

https://bugzilla.redhat.com/show_bug.cgi?id=1276911#c7

**Comment by chris1984** [comment]
Going to work on this, I can't assign myself though. @iNecas can you set me as assignee, please?

**Comment by swapab** [comment]
Redmine issue: http://projects.theforeman.org/issues/19710
