### ISSUE TITLE
Command: Storage Planning

### ISSUE THREAD

**Issue by sideangleside** [theforeman/foreman_maintain#42]
As a user, I'd like the ability to plan how much storage I'd need for repositories that I plan to synchronize, taking into account that Pulp only stores the RPM once on disk. Basically, I'd want a tool like [pulp-planner](https://github.com/RedHatSatellite/pulp-planner), but with the capability of gathering this information for both Red Hat and non Red Hat repositories.

**Comment by kgaikwad** [comment]
Tracking as http://projects.theforeman.org/issues/20152, closing the issue as we are moving away from github issue tracker to Redmine http://projects.theforeman.org/projects/foreman-maintain.
