### ISSUE TITLE
Check: Verify if iSCSI is mounted before services

### ISSUE THREAD

**Issue by lzap** [theforeman/foreman_maintain#80]
Experience from field engineering customer. When data folders are mounted over NFS or iSCSI, we need to query systemd if RequiresMountsFor is set. Prefered method of configuring that is via .d directory so it won't get overwritten by the installer:

```
# cat /etc/systemd/system/postgresql.service.d/mounts.conf
[Unit]
RequiresMountsFor=/var/lib/pgsql
```

Do not grep the file directly, use `systemctl show postgresql.service | grep RequiresMountsFor` to find out, in case it appears in `mount` output.

Typical services affected:

* postgresql
* mongod
* pulp data

**Comment by kgaikwad** [comment]
Tracking in Redmine: http://projects.theforeman.org/issues/20523 so closing the issue.
